### ISSUE TITLE
Please stop

### ISSUE THREAD

**Issue by DylanGTech** [RochesterJournalist/DylanGreenRIT#1]
I would appreciate it if you ceased the stalking of my online (and in some cases, real-world) presense and making up lies about me. That would make things very good for everyone.

**Comment by RochesterJournalist** [comment]
Hello Dylan,

Thanks for reaching out with your concerns. I just want to up front say nobody related to this repository or our website is stalking you. We actually had pretty much forgotten about this repo until you posted this issue. So rest assured that at least from our end we are not and will not do anything of the sort. Archiving hate speech you posted publicly is not stalking by any stretch.

As far as the content of this repo and related website goes, all of it is factual to the best of our knowledge. If there is anything that is untrue please open an issue in this repository and we will be sure to investigate it and remove any incorrect information.

Additionally we do not wish to cause you undue hardship if you decide to change your views in the future. We will revisit this information periodically to verify that it is still in line with the views you post online and spread on campus; if they are not we will of course take down the site and information so that you can move on without it hanging over you.

As of today though you are still posting material that attempts to encourage discrimination against minorities in protected classes (per NY state law), so we will keep the site and this repository up.

We hope that you can find the motivation to befriend some of the people you seem to dislike (Jewish people, LGBT people, left-leaning people, etc) you might find that you have more in common that you would expect, and you might also find that we are not the horrible people you seem to thing we are.

We wish you well!

**Comment by DylanGTech** [comment]
Might I please have the names, social media accounts, and status at RIT for the creators of this project? I would like to create a similar repository. There are legal ways of finding out, but I would prefer not to do so.

**Comment by DylanGTech** [comment]
I have also multiple friends who are Jewish and LGBT: 3 are Jewish, one of which is at RIT. 1 of which is a former homosexual. Another is a present-day homosexual, but is still finding his way. I may bring them on here soon to say the same "hate speech" I say if you so wish.

**Comment by RochesterJournalist** [comment]
In the interest of protecting individuals from harm we will refrain from sharing their personal information.

Of course you are free to try legal avenues but given that no laws are broken you will not be able to get any information that way, but again you are more than welcome to try.

**Comment by DylanGTech** [comment]
You are continually harming me right now. Do you believe this is somehow different and that you are protected from the same criticism?

**Comment by DylanGTech** [comment]
You are openly and avidly causing me harm.

Sent via the Samsung Galaxy S20 FE 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
